// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBD2_IjILply77v-xR8ILywJQD-cqyg_Ng',
    appId: '1:258494958396:web:f936b6b2647492d388ac39',
    messagingSenderId: '258494958396',
    projectId: 'hathiapp-5180a',
    authDomain: 'hathiapp-5180a.firebaseapp.com',
    storageBucket: 'hathiapp-5180a.appspot.com',
    measurementId: 'G-0EM70E5DEH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmR9QcGhgPXRGnxREgzMH1e4NB1hVNvgY',
    appId: '1:258494958396:android:301acb2eec4619e788ac39',
    messagingSenderId: '258494958396',
    projectId: 'hathiapp-5180a',
    storageBucket: 'hathiapp-5180a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFLkwERmGINMxWMQxNGxBCjblYbr_rr6c',
    appId: '1:258494958396:ios:cb33ff186a01f38488ac39',
    messagingSenderId: '258494958396',
    projectId: 'hathiapp-5180a',
    storageBucket: 'hathiapp-5180a.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFLkwERmGINMxWMQxNGxBCjblYbr_rr6c',
    appId: '1:258494958396:ios:cb33ff186a01f38488ac39',
    messagingSenderId: '258494958396',
    projectId: 'hathiapp-5180a',
    storageBucket: 'hathiapp-5180a.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
